CREATE TABLE Enemies (
    EnemyID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL,
    HP INT NOT NULL,
    MaxHP INT NOT NULL,
    XP INT NOT NULL,
    Loot NVARCHAR(50) NULL,
    Mana INT DEFAULT 0,
    MaxMana INT DEFAULT 0
);
