CREATE TABLE DungeonLog (
    LogID INT IDENTITY(1,1) NOT NULL,
    CharID INT NOT NULL,
    Message VARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    CONSTRAINT PK_DungeonLog PRIMARY KEY (LogID)
);
